<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/30 21:41:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=kettle_mr',
  'username' => 'root',
  'password' => 'conch',
  'name' => 'doctrine',
)),);
