<?php

/**
 * BusinessLogicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BusinessLogicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BusinessLogicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BusinessLogic');
    }
}