<?php

/**
 * ColumnStatsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ColumnStatsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ColumnStatsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ColumnStats');
    }
}