<?php

/**
 * FormulaColumnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormulaColumnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormulaColumnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormulaColumn');
    }
}