<?php

/**
 * LogicalColumnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogicalColumnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogicalColumnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogicalColumn');
    }
}