<?php

/**
 * SchemaTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SchemaTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SchemaTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SchemaType');
    }
}