<?php

/**
 * SchemaListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SchemaListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SchemaListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SchemaList');
    }
}