<?php

/**
 * TableColumnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TableColumnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TableColumnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TableColumn');
    }
}