<?php

/**
 * BaseBusinessFormulaLogic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $business_formula_logic_id
 * @property integer $formula_name
 * @property string $formula_description
 * @property Doctrine_Collection $TableColumn
 * @property Doctrine_Collection $FormulaColumnUsageType
 * @property Doctrine_Collection $BusinessFormulaLogicFormulaColumnFk
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBusinessFormulaLogic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('business_formula_logic');
        $this->hasColumn('business_formula_logic_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('formula_name', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('formula_description', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TableColumn', array(
             'refClass' => 'FormulaColumn',
             'local' => 'business_formula_logic_id',
             'foreign' => 'table_column_business_formula_logic_id'));

        $this->hasMany('FormulaColumnUsageType', array(
             'refClass' => 'FormulaColumn',
             'local' => 'business_formula_logic_id',
             'foreign' => 'formula_column_usage_type_business_formula_logic_id'));

        $this->hasMany('FormulaColumn as BusinessFormulaLogicFormulaColumnFk', array(
             'local' => 'business_formula_logic_id',
             'foreign' => 'business_formula_logic_id'));
    }
}