<?php

/**
 * BaseSchemaList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $schema_id
 * @property string $schema_database_type
 * @property string $server
 * @property integer $schema_type_id
 * @property SchemaType $SchemaTypeId
 * @property Doctrine_Collection $SchemaTableFk
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchemaList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('schema_list');
        $this->hasColumn('schema_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('schema_database_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('server', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('schema_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SchemaType as SchemaTypeId', array(
             'local' => 'schema_type_id',
             'foreign' => 'schema_type_id'));

        $this->hasMany('TableName as SchemaTableFk', array(
             'local' => 'schema_id',
             'foreign' => 'schema_id'));
    }
}