<?php

/**
 * BaseSchemaType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $schema_type_id
 * @property string $schema_type
 * @property Doctrine_Collection $SchemaTypeSchemaListFk
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchemaType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('schema_type');
        $this->hasColumn('schema_type_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('schema_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SchemaList as SchemaTypeSchemaListFk', array(
             'local' => 'schema_type_id',
             'foreign' => 'schema_type_id'));
    }
}