<?php

/**
 * BaseLogicalColumn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $column_id
 * @property integer $business_logic_id
 * @property TableColumn $ColumnId
 * @property BusinessLogic $BusinessLogicId
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogicalColumn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logical_column');
        $this->hasColumn('column_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('business_logic_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TableColumn as ColumnId', array(
             'local' => 'column_id',
             'foreign' => 'column_id'));

        $this->hasOne('BusinessLogic as BusinessLogicId', array(
             'local' => 'business_logic_id',
             'foreign' => 'business_logic_id'));
    }
}