<?php

/**
 * BaseFormulaColumn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $column_id
 * @property integer $business_formula_logic_id
 * @property integer $column_usage
 * @property integer $formula_column_usage_type_id
 * @property TableColumn $ColumnId
 * @property BusinessFormulaLogic $BusinessFormulaLogicId
 * @property FormulaColumnUsageType $FormulaColumnUsageTypeId
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormulaColumn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formula_column');
        $this->hasColumn('column_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('business_formula_logic_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('column_usage', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('formula_column_usage_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TableColumn as ColumnId', array(
             'local' => 'column_id',
             'foreign' => 'column_id'));

        $this->hasOne('BusinessFormulaLogic as BusinessFormulaLogicId', array(
             'local' => 'business_formula_logic_id',
             'foreign' => 'business_formula_logic_id'));

        $this->hasOne('FormulaColumnUsageType as FormulaColumnUsageTypeId', array(
             'local' => 'formula_column_usage_type_id',
             'foreign' => 'formula_column_usage_type_id'));
    }
}