<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/30 20:13:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=kettle-mr',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
